AllCops:
  TargetRubyVersion: 2.6

Metrics/AbcSize:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Metrics/ClassLength:
  Max: 400

Metrics/BlockLength:
  ExcludedMethods:
    - describe
    - context

Style/NegatedIf:
  Enabled: false

Layout/IndentHeredoc:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false
