AllCops:
  TargetRubyVersion: 2.6

Metrics/AbcSize:
  Enabled: false

Layout/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 15

Metrics/ClassLength:
  Max: 400

Metrics/BlockLength:
  ExcludedMethods:
    - describe
    - context

Style/NegatedIf:
  Enabled: false

Layout/HeredocIndentation:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/BracesAroundHashParameters:
  EnforcedStyle: braces
