AllCops:
  TargetRubyVersion: 2.6

Layout/HeredocIndentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods:
    - context
    - describe

Metrics/ClassLength:
  Max: 400

Layout/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 15

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/MultilineBlockChain:
  Enabled: false

Style/NegatedIf:
  Enabled: false

