name             'iptables_config'
maintainer       'Yaroslavl FRUCT Laboratory'
maintainer_email 'yarfruct@gmail.com'
license          'All rights reserved'
description      'Installs and configures the iptables util depending on the system'
version          '0.1.0'
