name             'mdbci-docker'
maintainer       'mariadb-corporation'
maintainer_email 'evgeny.vlasov@fruct.org'
license          'All rights reserved'
description      'Install Docker as product at VM'
version          '0.1.0'
depends          'docker'
