name             'kafka'
maintainer       'Yaroslavl FRUCT Laboratory'
maintainer_email 'yarfruct@gmail.com'
license          'All rights reserved'
description      'Provides unified platform for handling real-time data feeds'
version          '0.1.0'
