mariadb:
  repo:
    rpm:
      path: http://yum.mariadb.org/
      key: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    deb:
      path: http://mirror.netinch.com/pub/mariadb/repo/
      key: "0xF1656F24C74CD1D8"
columnstore:
  repo:
    rpm:
      path: https://downloads.mariadb.com/ColumnStore/
      key: https://downloads.mariadb.com/ColumnStore/MariaDB-ColumnStore.gpg.key
    deb:
      path: https://downloads.mariadb.com/ColumnStore/
      key: "AD0DEAFDA41F5C14"
maxscale_ci:
  repo:
    rpm:
      path: http://max-tst-01.mariadb.com/ci-repository/
      key: https://downloads.mariadb.com/MaxScale/MariaDB-MaxScale-GPG-KEY
    deb:
      path: http://max-tst-01.mariadb.com/ci-repository/
      key: "135659e928c12247"
maxscale:
  path: https://dlm.mariadb.com/browse/mariadbmaxscale/
mdbe:
  repo:
    rpm:
      path: https://dlm.mariadb.com/browse/$PRIVATE_KEY$/mariadb_enterprise_server/
      key: https://downloads.mariadb.com/MariaDB/MariaDB-Enterprise-GPG-KEY
      baseurl: https://dlm.mariadb.com/repo/$PRIVATE_KEY$/mariadb-enterprise-server/$MDBE_VERSION$/rpm/rhel/$releasever/$basearch
      platforms: ["centos_6", "centos_7", "centos_8", "rhel_6", "rhel_7", "rhel_8"]
    deb:
      path: https://dlm.mariadb.com/browse/$PRIVATE_KEY$/mariadb_enterprise_server/
      key: ["0x70E4618A8167EE24", "0xCE1A3DD5E3C94f49", "0xCBCB082A1BB943DB", "0xF1656F24C74CD1D8", "0x135659E928C12247"]
      baseurl: https://dlm.mariadb.com/repo/$PRIVATE_KEY$/mariadb-enterprise-server/$MDBE_VERSION$/deb
      platforms: ["debian_jessie", "debian_stretch", "ubuntu_xenial", "ubuntu_bionic"]
mysql:
  repo:
    rpm:
      path: http://repo.mysql.com/yum/
      key: http://repo.mysql.com/RPM-GPG-KEY-mysql
    deb:
      path: http://repo.mysql.com/apt/
      key: "5072E1F5"
clustrix:
  path: http://files.clustrix.com/releases/software/clustrix-$VERSION$.el7.tar.bz2
  platforms: ["centos_7"]
  versions: ["9.1.2", "9.1.3", "9.1.4"]
