mariadb:
  rpm:
    path: https://dlm.mariadb.com/browse/mariadb_server/
    key: https://downloads.mariadb.com/MariaDB/MariaDB-Server-GPG-KEY
  deb:
    path: https://dlm.mariadb.com/browse/mariadb_server/
    key: ["0x8167EE24", "0xE3C94F49", "0xcbcb082a1bb943db", "0xf1656f24c74cd1d8", "0x135659e928c12247"]
maxscale_ci:
  repo:
    path: https://mdbe-ci-repo.mariadb.net/Maxscale/
    old_key: https://mdbe-ci-repo.mariadb.net/MariaDBManager-GPG-KEY.public
    new_key: https://mdbe-ci-repo.mariadb.net/MDBE.public
maxscale_enterprise_ci:
  repo:
    path: https://mdbe-ci-repo.mariadb.net/MaxscaleEnterprise/
    old_key: https://mdbe-ci-repo.mariadb.net/MariaDBManager-GPG-KEY.public
    new_key: https://mdbe-ci-repo.mariadb.net/MDBE.public
maxscale:
  rpm:
    path: https://dlm.mariadb.com/browse/mariadbmaxscale/
    key: https://downloads.mariadb.com/MariaDB/MariaDB-Enterprise-GPG-KEY
  deb:
    path: https://dlm.mariadb.com/browse/mariadbmaxscale/
    key: ["0x8167EE24", "0xE3C94F49", "0xcbcb082a1bb943db", "0xf1656f24c74cd1d8", "0x135659e928c12247"]
mdbe:
  repo:
    rpm:
      path: https://dlm.mariadb.com/browse/$PRIVATE_KEY$/mariadb_enterprise_server/
      key: https://downloads.mariadb.com/MariaDB/MariaDB-Enterprise-GPG-KEY
      baseurl: https://dlm.mariadb.com/repo/$PRIVATE_KEY$/mariadb-enterprise-server/$MDBE_VERSION$/rpm/$PLATFORM$/$PLATFORM_VERSION$/$basearch
      platforms: ["centos_6", "centos_7", "centos_8", "rhel_6", "rhel_7", "rhel_8", "rhel_9", "sles_12", "sles_15"]
      architectures: ["amd64", "aarch64", "ppc64le"]
    deb:
      path: https://dlm.mariadb.com/browse/$PRIVATE_KEY$/mariadb_enterprise_server/
      key: ["0x70E4618A8167EE24", "0xCE1A3DD5E3C94f49", "0xCBCB082A1BB943DB", "0xF1656F24C74CD1D8", "0x135659E928C12247"]
      baseurl: https://dlm.mariadb.com/repo/$PRIVATE_KEY$/mariadb-enterprise-server/$MDBE_VERSION$/deb
      platforms: ["debian_jessie", "debian_stretch", "debian_buster", "debian_bullseye", "debian_bookworm", "ubuntu_xenial", "ubuntu_bionic", "ubuntu_focal", "ubuntu_jammy", "ubuntu_noble"]
      architectures: ["amd64", "aarch64"]
mysql:
  repo:
    rpm:
      path: http://repo.mysql.com/yum/
      key: http://repo.mysql.com/RPM-GPG-KEY-mysql
    deb:
      path: http://repo.mysql.com/apt/
      key: "5072E1F5"
clustrix:
  repo:
    path: https://dlm.mariadb.com/browse/$PRIVATE_KEY$/xpand/
clustrix_staging:
  repo:
    path: https://dlm.mariadb.com/browse/$PRIVATE_KEY$/xpand_staging/
mdbe_ci:
  repo:
    mdbe_ci_repo:
      path: https://mdbe-ci-repo.mariadb.net/MariaDBEnterprise/
      key: https://mdbe-ci-repo.mariadb.net/MDBE.public
    es_repo:
      path: https://es-repo.mariadb.net/jenkins/
      key: https://es-repo.mariadb.net/jenkins/MDBE.public
    cs_repo:
      path: https://cspkg.s3.amazonaws.com/
      yum_key: http://yum.mariadb.org/
      branches: ["develop-23.02/cron", "develop-23.02/pull_request", "develop-22.08/cron", 
                 "develop-22.08/pull_request", "develop/cron", "develop/pull_request", 
                 "stable-23.10/cron", "stable-23.10/pull_request", "custom"]
      latest_branches: ["develop-23.02", "develop-22.08", "develop", "stable-23.10"]
galera_3_community:
  repo:
    path: https://mdbe-ci-repo.mariadb.net/MariaDBGalera3/
    key: https://mdbe-ci-repo.mariadb.net/MDBE.public
galera_4_community:
  repo:
    path: https://mdbe-ci-repo.mariadb.net/MariaDBGalera4/
    key: https://mdbe-ci-repo.mariadb.net/MDBE.public
galera_3_enterprise:
  repo:
    path: https://mdbe-ci-repo.mariadb.net/MariaDBGalera3Enterprise/
    key: https://mdbe-ci-repo.mariadb.net/MDBE.public
galera_4_enterprise:
  repo:
    path: https://mdbe-ci-repo.mariadb.net/MariaDBGalera4Enterprise/
    key: https://mdbe-ci-repo.mariadb.net/MDBE.public
mariadb_ci:
  repo:
    path: https://mdbe-ci-repo.mariadb.net/MariaDBServerCommunity/
    key: https://mdbe-ci-repo.mariadb.net/MDBE.public
mdbe_staging:
  repo:
    rpm:
      path: https://dlm.mariadb.com/browse/$PRIVATE_KEY$/mariadb_enterprise_server_staging/
      key: https://downloads.mariadb.com/MariaDB/MariaDB-Enterprise-GPG-KEY
      baseurl: https://dlm.mariadb.com/repo/$PRIVATE_KEY$/mariadb-enterprise-staging/$MDBE_VERSION$/rpm/$PLATFORM$/$PLATFORM_VERSION$/$basearch
      platforms: ["centos_6", "centos_7", "centos_8", "rhel_6", "rhel_7", "rhel_8", "rhel_9", "sles_12", "sles_15"]
      architectures: ["amd64", "aarch64"]
    deb:
      path: https://dlm.mariadb.com/browse/$PRIVATE_KEY$/mariadb_enterprise_server_staging/
      key: ["0x70E4618A8167EE24", "0xCE1A3DD5E3C94f49", "0xCBCB082A1BB943DB", "0xF1656F24C74CD1D8", "0x135659E928C12247"]
      baseurl: https://dlm.mariadb.com/repo/$PRIVATE_KEY$/mariadb-enterprise-staging/$MDBE_VERSION$/deb
      platforms: ["debian_jessie", "debian_stretch", "debian_buster", "debian_bullseye", "debian_bookworm", "ubuntu_xenial", "ubuntu_bionic", "ubuntu_focal",  "ubuntu_jammy", "ubuntu_noble"]
      architectures: ["amd64", "aarch64"]
mariadb_staging:
  repo:
    rpm:
      path: https://downloads.mariadb.com/mariadb-staging/
      key: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    deb:
      path: https://downloads.mariadb.com/mariadb-staging/
      key: "0xF1656F24C74CD1D8"
connector_c_ci:
  repo:
    path: https://mdbe-ci-repo.mariadb.net/ConnectorC/
    key: https://mdbe-ci-repo.mariadb.net/MDBE.public
connector_cpp_ci:
  repo:
    path: https://mdbe-ci-repo.mariadb.net/ConnectorCpp/
    key: https://mdbe-ci-repo.mariadb.net/MDBE.public
connector_odbc_ci:
  repo:
    path: https://mdbe-ci-repo.mariadb.net/ConnectorODBC/
    key: https://mdbe-ci-repo.mariadb.net/MDBE.public
connector_odbc:
  repo:
    path: https://dlm.mariadb.com/browse/odbc_connector/
connector_odbc_staging:
  repo:
    path: https://dlm.mariadb.com/browse/$PRIVATE_KEY$/odbc_connector_staging/
kafka:
  repo:
    path: https://dlcdn.apache.org/kafka/
