--- # Network resources for verification
- https://github.com
- https://www-eu.apache.org/
- https://nodejs.org/
- http://prdownloads.sourceforge.net/
- https://yum.dockerproject.org/repo
- https://download.docker.com/linux
