# frozen_string_literal: true

require 'date'
require 'socket'
require 'erb'
require_relative '../../models/result'

# The class generates the Terraform infrastructure file for AWS provider
class TerraformAwsGenerator
  # Initializer.
  # @param configuration_id [String] configuration id
  # @param aws_config [Hash] hash of AWS configuration
  # @param logger [Out] logger
  # @param configuration_path [String] path to directory of generated configuration
  # @param ssh_keys [Hash] ssh keys info in format { public_key_value, private_key_file_path }
  # @return [Result::Base] generation result.
  def initialize(configuration_id, aws_config, logger, configuration_path, ssh_keys)
    @configuration_id = configuration_id
    @configuration_tags = { configuration_id: @configuration_id }
    @aws_config = aws_config
    @ui = logger
    @configuration_path = configuration_path
    @public_key_value = ssh_keys[:public_key_value]
    @private_key_file_path = ssh_keys[:private_key_file_path]
  end

  # Generate a Terraform configuration file.
  # @param node_params [Array<Hash>] list of node params
  # @param configuration_file_path [String] path to generated Terraform infrastructure file
  # @return [Result::Base] generation result.
  # rubocop:disable Metrics/MethodLength
  def generate_configuration_file(node_params, configuration_file_path)
    raise 'AWS is not configured' if @aws_config.nil?

    need_vpc = false
    file = File.open(configuration_file_path, 'w')
    file.puts(file_header)
    file.puts(provider_resource)
    node_params.each do |node|
      print_node_info(node)
      file.puts(generate_node_definition(node))
      need_vpc = true if node[:vpc]
    end
    file.puts(vpc_resources) if need_vpc
    file.close
  rescue Errno::ENOENT => e
    Result.error(e.message)
  else
    Result.ok('')
  end
  # rubocop:enable Metrics/MethodLength

  # Generate key pair name by configuration id.
  # The name includes an identifier, host name,
  # and configuration name to identify the owner of the key.
  #
  # @param configuration_id [String] configuration id
  # @return [String] key pair name
  def self.generate_key_pair_name(configuration_id, configuration_path)
    hostname = Socket.gethostname
    config_name = File.basename(configuration_path)
    "#{configuration_id}-#{config_name}-#{hostname}"
  end

  private

  # Log the information about the main parameters of the node.
  #
  # @param node_params [Hash] list of the node parameters
  def print_node_info(node_params)
    @ui.info("AWS definition for host:#{node_params[:host]}, ami:#{node_params[:ami]}, user:#{node_params[:user]}")
  end

  def file_header
    <<-HEADER
    # !! Generated content, do not edit !!
    # Generated by MariaDB Continuous Integration Tool (https://github.com/mariadb-corporation/mdbci)
    #### Created #{Time.now} ####
    HEADER
  end

  def provider_resource
    <<-PROVIDER
    provider "aws" {
      version = "~> 2.33"
      profile = "default"
      region = "#{@aws_config['region']}"
      access_key = "#{@aws_config['access_key_id']}"
      secret_key = "#{@aws_config['secret_access_key']}"
    }
    locals {
      cidr_vpc = "10.1.0.0/16" # CIDR block for the VPC
      cidr_subnet = "10.1.0.0/24" # CIDR block for the subnet
      availability_zone = "#{@aws_config['availability_zone']}" # availability zone to create subnet
    }
    #{key_pair_resource}
    #{security_group_resource(false)}
    PROVIDER
  end

  def vpc_resources
    <<-VPC_RESOURCES
    resource "aws_vpc" "vpc" {
      cidr_block = local.cidr_vpc
      enable_dns_support = true
      enable_dns_hostnames = true
      #{tags_partial(@configuration_tags)}
    }
    resource "aws_internet_gateway" "igw" {
      vpc_id = aws_vpc.vpc.id
      #{tags_partial(@configuration_tags)}
    }
    resource "aws_subnet" "subnet_public" {
      vpc_id = aws_vpc.vpc.id
      cidr_block = local.cidr_subnet
      map_public_ip_on_launch = true
      availability_zone = local.availability_zone
      #{tags_partial(@configuration_tags)}
    }
    resource "aws_route_table" "rtb_public" {
      vpc_id = aws_vpc.vpc.id
      route {
          cidr_block = "0.0.0.0/0"
          gateway_id = aws_internet_gateway.igw.id
      }
      #{tags_partial(@configuration_tags)}
    }
    resource "aws_route_table_association" "rta_subnet_public" {
      subnet_id = aws_subnet.subnet_public.id
      route_table_id = aws_route_table.rtb_public.id
    }
    #{security_group_resource(true)}
    VPC_RESOURCES
  end

  # Generate a connection block for AWS instance resource.
  # @param user [String] user name of instance
  # @return [String] connection block definition.
  def connection_partial(user)
    <<-PARTIAL
    connection {
      type = "ssh"
      private_key = file("#{@private_key_file_path}")
      timeout = "10m"
      agent = false
      user = "#{user}"
      host = self.public_ip
    }
    PARTIAL
  end

  def tags_partial(tags)
    template = ERB.new <<-PARTIAL
    tags = {
      <% tags.each do |tag_key, tag_value| %>
          <%= tag_key %> = "<%= tag_value %>"
        <% end %>
      }
    PARTIAL
    template.result(binding)
  end

  # Generate a security_group resource definition for AWS infrastructure.
  # @param vpc [Boolean] true if it's vpc security group
  # @return [String] security group resource definition.
  # rubocop:disable Metrics/MethodLength
  def security_group_resource(vpc)
    group_name = "#{Socket.gethostname}_#{Time.now.strftime('%s')}"
    tags_block = tags_partial(@configuration_tags)
    template = ERB.new <<-SECURITY_GROUP
    resource "aws_security_group" "security_group<%= vpc ? '_vpc' : '' %>" {
      name = "<%= group_name %>"
      description = "MDBCI <%= group_name %> auto generated"
      ingress {
        from_port = 0
        <% if vpc %>
          protocol = "-1"
          to_port = 0
        <% else %>
          protocol = "tcp"
          to_port = 65535
        <% end %>
        cidr_blocks = ["0.0.0.0/0"]
      }
      <% if vpc %>
        vpc_id = aws_vpc.vpc.id
        egress {
          from_port = 0
          to_port = 0
          protocol = -1
          cidr_blocks = ["0.0.0.0/0"]
        }
      <% end %>
      <%= tags_block %>
    }
    SECURITY_GROUP
    template.result(binding)
  end
  # rubocop:enable Metrics/MethodLength

  # Generate Terraform configuration resources for instance.
  # @param node_params [Hash] list of the node parameters
  # @return [String] generated resources for instance.
  # rubocop:disable Metrics/MethodLength
  def instance_resources(node_params)
    connection_block = connection_partial(node_params[:user])
    tags_block = tags_partial(node_params[:tags])
    key_file = @private_key_file_path
    template = ERB.new <<-AWS
    resource "aws_instance" "<%= name %>" {
      ami = "<%= ami %>"
      instance_type = "<%= default_instance_type %>"
      key_name = aws_key_pair.ec2key.key_name
      <% if vpc %>
        vpc_security_group_ids = [aws_security_group.security_group_vpc.id]
        subnet_id = aws_subnet.subnet_public.id
        depends_on = [aws_route_table_association.rta_subnet_public, aws_route_table.rtb_public]
      <% else %>
        security_groups = ["default", aws_security_group.security_group.name]
      <% end %>
      <%= tags_block %>
      root_block_device {
        volume_size = 500
      }
      <%= connection_block %>
      user_data = <<-EOT
      #!/bin/bash
      sed -i -e 's/^Defaults.*requiretty/# Defaults requiretty/g' /etc/sudoers
      EOT
      <% if template_path %>
        provisioner "remote-exec" {
          inline = [
            "mkdir -p /home/<%= user %>/cnf_templates",
            "sudo mkdir /vagrant",
            "sudo bash -c 'echo \\"<%= provider %>\\" > /vagrant/provider'"
          ]
        }
        provisioner "file" {
          source = "<%= template_path %>"
          destination = "/home/<%= user %>/cnf_templates"
        }
        provisioner "remote-exec" {
          inline = [
            "sudo mkdir -p /home/vagrant/",
            "sudo mv /home/<%= user %>/cnf_templates /home/vagrant/cnf_templates"
          ]
        }
      <% end %>
    }
    output "<%= name %>_network" {
      value = {
        user = "<%= user %>"
        private_ip = aws_instance.<%= name %>.private_ip
        public_ip = aws_instance.<%= name %>.public_ip
        key_file = "<%= key_file %>"
      }
    }
    AWS
    template.result(OpenStruct.new(node_params).instance_eval { binding })
  end
  # rubocop:enable Metrics/MethodLength

  def key_pair_resource
    key_pair_name = self.class.generate_key_pair_name(@configuration_id, @configuration_path)
    <<-KEY_PAIR_RESOURCE
    resource "aws_key_pair" "ec2key" {
      key_name = "#{key_pair_name}"
      public_key = "#{@public_key_value}"
    }
    KEY_PAIR_RESOURCE
  end

  # Generate a node definition for the configuration file.
  # @param node_params [Hash] list of the node parameters
  # @return [String] node definition for the configuration file.
  def generate_node_definition(node_params)
    tags = @configuration_tags.merge(hostname: Socket.gethostname,
                                     username: Etc.getlogin,
                                     machinename: node_params[:name],
                                     full_config_path: @configuration_path)
    instance_resources(node_params.merge(tags: tags))
  end
end
