# frozen_string_literal: true

require 'date'
require 'erb'
require 'socket'
require_relative '../../models/result'
require_relative '../../services/cloud_services'
require_relative '../../services/terraform_service'
require_relative '../../services/configuration_reader'

# The class generates the Terraform infrastructure file for Google Cloud Platform provider
class TerraformGcpGenerator
  # Initializer.
  # @param configuration_id [String] configuration id
  # @param gcp_config [Hash] hash of Google Cloud Platform configuration
  # @param logger [Out] logger
  # @param configuration_path [String] path to directory of generated configuration
  # @param ssh_keys [Hash] ssh keys info in format { public_key_value, private_key_file_path }
  # @param gcp_service [GcpService] Google Cloud Compute service
  # @param all_windows [Boolean] all machines on the Windows platform
  # @return [Result::Base] generation result.
  def initialize(configuration_id, gcp_config, logger, configuration_path, ssh_keys, gcp_service, all_windows)
    @configuration_id = configuration_id
    @gcp_config = gcp_config
    @ui = logger
    @configuration_path = configuration_path
    @configuration_labels = { configuration_id: @configuration_id,
                              full_config_path: TerraformService.format_string(@configuration_path, max_length: 60) }
    unless all_windows
      @public_key_value = ssh_keys[:public_key_value]
      @private_key_file_path = ssh_keys[:private_key_file_path]
      @user = ssh_keys[:login]
    end
    @gcp_service = gcp_service
  end

  # Generate a Terraform configuration file.
  # @param node_params [Array<Hash>] list of node params.
  # @param configuration_file_path [String] path to generated Terraform infrastructure file.
  # @return [Result::Base] generation result.
  def generate_configuration_file(node_params, configuration_file_path)
    return Result.error('Google Cloud Platform is not configured') if @gcp_config.nil?

    file = File.open(configuration_file_path, 'w')
    file.puts(file_header)
    file.puts(provider_resource)
    file.puts(vpc_resources) unless use_existing_network?
    result = Result.ok('')
    node_params.each do |node|
      result = generate_instance_params(node).and_then do |instance_params|
        print_node_info(instance_params)
        file.puts(instance_resources(instance_params))
        Result.ok('')
      end
      break if result.error?
    end
  rescue StandardError => e
    Result.error(e.message)
  else
    result
  ensure
    file.close unless file.nil? || file.closed?
  end

  # Generate the instance name.
  # @param configuration_id [String] configuration id.
  # @param node_name [String] name of the node.
  # @return [String] generated instance name.
  def self.generate_instance_name(configuration_id, node_name)
    "#{configuration_id}-#{TerraformService.format_string(node_name)}"
  end

  # Generate the vpc network name.
  # @param configuration_id [String] configuration id.
  # @return [String] generated network name.
  def self.generate_network_name(configuration_id)
    "#{configuration_id}-network"
  end

  # Generate the firewall name.
  # @param configuration_id [String] configuration id.
  # @return [String] generated firewall name.
  def self.generate_firewall_name(configuration_id)
    "#{configuration_id}-firewall"
  end

  private

  # Log the information about the main parameters of the node.
  # @param node_params [Hash] list of the node parameters.
  def print_node_info(node_params)
    @ui.info("Google Cloud Platform definition for host: #{node_params[:host]}, "\
             "image:#{node_params[:image]}, machine_type:#{node_params[:machine_type]}")
  end

  def file_header
    <<-HEADER
    # !! Generated content, do not edit !!
    # Generated by MariaDB Continuous Integration Tool (https://github.com/mariadb-corporation/mdbci)
    #### Created #{Time.now} ####
    HEADER
  end

  # Generate provider resource.
  def provider_resource
    <<-PROVIDER
    terraform {
      required_providers {
        google = {
          source = "hashicorp/google"
          version = ">= 3.65.0"
        }
      }
    }

    provider "google" {
      credentials = file("#{@gcp_config['credentials_file']}")
      project = "#{@gcp_config['project']}"
      region = "#{@gcp_config['region']}"
      zone = "#{@gcp_config['zone']}"
    }
    PROVIDER
  end

  # Generate fields for setting ssh in the metadata block of instance.
  # @return [String] generated fields.
  def ssh_data
    <<-SSH_DATA
    ssh-keys = "#{@user}:#{@public_key_value}}"
    enable-oslogin = "FALSE"
    SSH_DATA
  end

  # Generate vpc resources.
  # @return [String] generated resources for vpc.
  def vpc_resources
    firewall_name = self.class.generate_firewall_name(@configuration_id)
    <<-VPC_RESOURCES
    resource "google_compute_network" "vpc_network" {
      name = "#{network_name}"
    }
    resource "google_compute_firewall" "firewall_rules" {
      name = "#{firewall_name}"
      description = "Allow all traffic"
      network = google_compute_network.vpc_network.name
      allow {
        protocol = "icmp"
      }
      allow {
        protocol = "tcp"
        ports = ["0-65535"]
      }
      allow {
        protocol = "udp"
        ports = ["0-65535"]
      }
      source_ranges = ["0.0.0.0/0"]
      target_tags = ["allow-all-traffic"]
    }
    VPC_RESOURCES
  end

  # Generate instance resources.
  # @param instance_params [Hash] list of the instance parameters
  # @return [String] generated resources for instance.
  # rubocop:disable Metrics/MethodLength
  def instance_resources(instance_params)
    if instance_params[:platform] == 'windows'
      need_metadata = false
    else
      need_metadata = true
      ssh_metadata = ssh_data
    end
    tags_block = tags_partial(instance_tags)
    labels_block = labels_partial(instance_params[:labels])
    template = ERB.new <<-INSTANCE_RESOURCES
    resource "google_compute_instance" "<%= name %>" {
      name = "<%= instance_name %>"
      machine_type = "<%= machine_type %>"
      <%= tags_block %>
      <%= labels_block %>
      boot_disk {
        initialize_params {
          image = "<%= image %>"
          size = 500
        }
      }
      <% if is_own_vpc %>
        depends_on = [google_compute_network.vpc_network, google_compute_firewall.firewall_rules]
      <% end %>
      network_interface {
        network = "<%= network %>"
        <% unless use_only_private_ip %>
          access_config {
          }
        <% end %>
      }
      <% if preemptible %>
        scheduling {
          preemptible = true
          automatic_restart = false
        }
      <% end %>
      <% if need_metadata %>
        metadata = {
          <%= ssh_metadata %>
        }
      <% end %>
    }
    output "<%= name %>_network" {
      value = {
        user = "<%= user %>"
        private_ip = google_compute_instance.<%= name %>.network_interface.0.network_ip
        <% if use_only_private_ip %>
          public_ip = google_compute_instance.<%= name %>.network_interface.0.network_ip
        <% else %>
          public_ip = google_compute_instance.<%= name %>.network_interface.0.access_config.0.nat_ip
        <% end %>
        key_file = "<%= key_file %>"
        hostname = "<%= instance_name %>"
      }
    }
    INSTANCE_RESOURCES
    template.result(OpenStruct.new(instance_params).instance_eval { binding })
  end
  # rubocop:enable Metrics/MethodLength

  # Generate a labels block.
  # @param labels [Hash] list of labels in format { label_name: label_value }
  # @return [String] labels block definition.
  def labels_partial(labels)
    template = ERB.new <<-PARTIAL
    labels = {
      <% labels.each do |label_key, label_value| %>
          <%= label_key %> = "<%= label_value %>"
        <% end %>
      }
    PARTIAL
    template.result(binding)
  end

  # Generate a tags block.
  # @param tags [Array<String>] list of tags
  # @return [String] tags block definition.
  def tags_partial(tags)
    "tags = [#{tags.map { |tag| "\"#{tag}\"" }.join(', ')}]"
  end

  # Returns false if a new vpc resources need to be generated for the current configuration, otherwise true.
  # @return [Boolean] result.
  def use_existing_network?
    @gcp_config['use_existing_network']
  end

  # Returns true if an external ip generation is not required for a new instance.
  # @return [Boolean] result.
  def use_only_private_ip?
    @gcp_config['use_only_private_ip']
  end

  # Returns network name for current configuration if a new vpc resources need to be generated for the current
  # configuration, otherwise returns network name configured in the mdbci configuration.
  # @return [String] network name.
  def network_name
    return self.class.generate_network_name(@configuration_id) unless use_existing_network?

    @gcp_config['network']
  end

  # Returns instance network tags for current configuration.
  # Returns generated new network tags if a new vpc resources need to be generated for the current
  # configuration, otherwise returns network tags configured in the mdbci configuration.
  # @return [Array<String>] list of instance tags.
  def instance_tags
    return ['allow-all-traffic'] unless use_existing_network?

    @gcp_config['tags']
  end

  # Generate a instance params for the configuration file.
  # @param node_params [Hash] list of the node parameters
  # @return [Result::Base] instance params
  def generate_instance_params(node_params)
    if node_params[:platform] == 'windows'
      user = 'jenkins'
      private_key_file_path = ConfigurationReader.path_to_user_file('mdbci/windows.pem')
      if private_key_file_path.nil?
        return Result.error('Please create the windows.pem file in the configuration directory')
      end
    else
      user = @user
      private_key_file_path = @private_key_file_path
    end
    labels = @configuration_labels.merge(hostname: TerraformService.format_string(Socket.gethostname),
                                         username: TerraformService.format_string(user),
                                         machinename: TerraformService.format_string(node_params[:name]))
    node_params = node_params.merge(
        labels: labels,
        instance_name: self.class.generate_instance_name(@configuration_id, node_params[:name]),
        network: network_name,
        user: user,
        is_own_vpc: !use_existing_network?,
        key_file: private_key_file_path,
        use_only_private_ip: use_only_private_ip?
    )
    machine_types = @gcp_service.machine_types_list
    CloudServices.choose_instance_type(machine_types, node_params).and_then do |machine_type|
      @gcp_service.check_quota(machine_types, machine_type, @ui).and_then do
        Result.ok(node_params.merge(machine_type: machine_type))
      end
    end
  end
end
