# frozen_string_literal: true

require 'date'
require 'fileutils'
require 'json'
require 'pathname'
require 'securerandom'
require 'socket'
require 'erb'
require 'set'
require_relative '../base_command'
require_relative '../../out'
require_relative '../../models/configuration.rb'
require_relative '../../services/shell_commands'
require_relative '../../../core/services/configuration_generator'
require_relative '../../services/product_attributes'

# The class generates the MDBCI configuration for use in pair with the Vagrant backend
# rubocop:disable Metrics/ClassLength
class VagrantConfigurationGenerator < BaseCommand
  CNF_PATH_FILE_NAME = 'cnf_path'

  def self.synopsis
    'Generate a configuration based on the template.'
  end

  def self.role_file_name(path, role)
    "#{path}/#{role}.json"
  end

  def self.node_config_file_name(path, role)
    "#{path}/#{role}-config.json"
  end

  def vagrant_file_header
    <<-HEADER
# !! Generated content, do not edit !!
# Generated by MariaDB Continuous Integration Tool (https://github.com/mariadb-corporation/mdbci)
#### Created #{Time.now} ####
    HEADER
  end

  def provider_config
    <<-CONFIG
### Default (VBox, Libvirt) Provider config ###
#######################################################
# Network autoconfiguration
config.vm.network "private_network", type: "dhcp"
config.vm.boot_timeout = 60
    CONFIG
  end

  def vagrant_config_header
    <<-HEADER
### Vagrant configuration block  ###
####################################
Vagrant.configure(2) do |config|
    HEADER
  end

  def vagrant_config_footer
    <<-FOOTER
end
### end of Vagrant configuration block
    FOOTER
  end

  # Vagrantfile for Vbox provider
  # rubocop:disable Metrics/MethodLength
  # The method returns a template; decomposition will complicate the code.
  def get_virtualbox_definition(_cookbook_path, node_params)
    template = ERB.new <<-VBOX
      config.vm.define '<%= name %>' do |box|
        box.vm.box = '<%= box %>'
        box.vm.hostname = '<%= host %>'
        <% if ssh_pty %>
           box.ssh.pty = <%= ssh_pty %>
        <% end %>
        box.vm.provider :virtualbox do |vbox|
          <% if vm_mem %>
             vbox.memory = <%= vm_mem %>
          <% end %>
          vbox.name = "\#{File.basename(File.dirname(__FILE__))}_<%= name %>"
        end
      end
    VBOX
    template.result(OpenStruct.new(node_params).instance_eval { binding })
  end
  # rubocop:enable Metrics/MethodLength

  # Vagrantfile for Libvirt provider
  # rubocop:disable Metrics/MethodLength
  # The method returns a template; decomposition will complicate the code.
  def get_libvirt_definition(_cookbook_path, path, node_params)
    node_params = node_params.merge(expand_path: File.expand_path(path), ipv6: @env.ipv6)
    template = ERB.new <<-LIBVIRT
      #  --> Begin definition for machine: <%= name %>
      config.vm.define '<%= name %>' do |box|
        box.vm.box = '<%= box %>'
        box.vm.hostname = '<%= host %>'
        <% if ssh_pty %>
          box.ssh.pty = <%= ssh_pty %>
        <% end %>
        <% if ipv6 %>
          box.vm.network :public_network, :dev => 'virbr0', :mode => 'bridge', :type => 'bridge'
        <% end %>
        box.vm.provider :libvirt do |qemu|
          qemu.driver = 'kvm'
          qemu.cpu_mode = 'host-passthrough'
          qemu.cpus = <%= vm_cpu %>
          qemu.memory = <%= vm_mem %>
        <% if disk_bus %>
          qemu.disk_bus = '<%= disk_bus %>'
        <% end %>
        end
        <% if platform == 'ubuntu' && platform_version == 'bionic' %>
        # Fix DNS bug
        script = <<-SCRIPT
          echo Fixing the netplan configuration
          sed -i '/nameservers:/d' /etc/netplan/01-netcfg.yaml
          sed -i '/addresses:/d' /etc/netplan/01-netcfg.yaml
          netplan apply
          echo Fixing systemd-resolved configuration
          echo "
[Resolve]
DNS=1.1.1.1
FallbackDNS=
Domains=
LLMNR=no
MulticastDNS=no
DNSSEC=no
Cache=no
DNSStubListener=yes" > /etc/systemd/resolved.conf
          systemctl restart systemd-resolved
          systemd-resolve --status
        SCRIPT

        box.vm.provision "shell", inline: script
        <% end %>
      end #  <-- End of Qemu definition for machine: <%= name %>
    LIBVIRT
    template.result(OpenStruct.new(node_params).instance_eval { binding })
  end
  # rubocop:enable Metrics/MethodLength

  # Make product config and recipe name for install it to the VM.
  #
  # @param product [Hash] parameters of product to configure from configuration file
  # @param box [String] name of the box
  # @return [Result::Base] recipe name and product config in format { recipe: String, config: Hash }.
  # rubocop:disable Metrics/MethodLength
  def make_product_config_and_recipe_name(product, box)
    repo = nil
    if !product['repo'].nil?
      repo_name = product['repo']
      @ui.info("Repo name: #{repo_name}")
      return Result.error("Unknown key for repo #{repo_name} will be skipped") unless @env.repos.knownRepo?(repo_name)

      @ui.info("Repo specified [#{repo_name}] (CORRECT), other product params will be ignored")
      repo = @env.repos.getRepo(repo_name)
      product_name = @env.repos.productName(repo_name)
    else
      product_name = product['name']
    end
    recipe_name = ProductAttributes.recipe_name(product_name)
    if product_name != 'packages'
      ConfigurationGenerator.generate_product_config(@env.repos, product_name, product, box, repo, @provider)
    else
      Result.ok({})
    end.and_then do |product_config|
      @ui.info("Recipe #{recipe_name}")
      Result.ok(recipe: recipe_name, config: product_config)
    end
  end
  # rubocop:enable Metrics/MethodLength

  # Initialize product configs Hash and recipe names list with necessary recipes
  # and configurations on which the box depends.
  #
  # @param box [String] name of the box
  # @return [Result::Base] Hash in format { recipe_names: [], product_configs: {} }
  def init_product_configs_and_recipes(box)
    product_configs = {}
    recipe_names = []

    if @env.box_definitions.get_box(box)['configure_subscription_manager'] == 'true'
      return Result.error('Credentials for Red Hat Subscription-Manager are not configured') if @env.rhel_config.nil?

      recipe_names << 'subscription-manager'
      product_configs.merge!('subscription-manager': @env.rhel_config)
    end

    if @env.box_definitions.get_box(box)['configure_suse_connect'] == 'true'
      return Result.error('Credentials for SUSEConnect are not configured') if @env.suse_config.nil?

      recipe_names << 'suse-connect'
      product_configs.merge!('suse-connect': @env.suse_config)
    end
    Result.ok({ product_configs: product_configs, recipe_names: recipe_names })
  end

  # Generate the role description for the specified node.
  #
  # @param name [String] internal name of the machine specified in the template
  # @param products [Array<Hash>] list of parameters of products to configure from configuration file
  # @param box [String] name of the box
  # @return [Result::Base<String>] pretty formatted role description in JSON format
  def get_role_description(name, products, box)
    recipes_result = init_product_configs_and_recipes(box)
    return recipes_result if recipes_result.error?

    product_configs = recipes_result.value[:product_configs]
    recipe_names = recipes_result.value[:recipe_names]
    products.each do |product|
      recipe_and_config_result = make_product_config_and_recipe_name(product, box)
      return recipe_and_config_result if recipe_and_config_result.error?

      recipe_and_config_result.and_then do |recipe_and_config|
        product_configs.merge!(recipe_and_config[:config])
        recipe_names << recipe_and_config[:recipe]
      end
    end
    role_description = ConfigurationGenerator.generate_role_json_description(name, recipe_names, product_configs)
    Result.ok(role_description)
  end

  # Check for the existence of a path, create it if path is not exists or clear path
  # if it is exists and override parameter is true.
  #
  # @param path [String] path of the configuration file
  # @param override [Bool] clean directory if it is already exists
  # @return [Bool] false if directory path is already exists and override is false, otherwise - true.
  def check_path(path, override)
    if Dir.exist?(path) && !override
      @ui.error("Folder already exists: #{path}. Please specify another name or delete")
      return false
    end
    FileUtils.rm_rf(path)
    Dir.mkdir(path)
    true
  end

  # Check for MDBCI node names defined in the template to be valid Ruby object names.
  #
  # @param config [Hash] value of the configuration file
  # @return [Bool] true if all nodes names are valid, otherwise - false.
  def check_nodes_names(config)
    invalid_names = config.map do |node|
      (node[0] =~ /^[a-zA-Z_]+[a-zA-Z_\d]*$/).nil? ? node[0] : nil
    end.compact
    return true if invalid_names.empty?

    @ui.error("Invalid nodes names: #{invalid_names}. "\
              'Nodes names defined in the template to be valid Ruby object names.')
    false
  end

  # Check for the box emptiness and existence of a box in the boxes list.
  #
  # @param box [String] name of the box
  def box_valid?(box)
    return false if box.empty?

    !@boxes.get_box(box).nil?
  end

  # Make a hash list of node parameters by a node configuration and
  # information of the box parameters.
  #
  # @param node [Array] information of the node from configuration file
  # @param box_params [Hash] information of the box parameters
  # @return [Hash] list of the node parameters.
  def make_node_params(node, box_params)
    symbolic_box_params = Hash[box_params.map { |k, v| [k.to_sym, v] }]
    {
      name: node[0].to_s,
      host: node[1]['hostname'].to_s,
      vm_mem: node[1]['memory_size'].nil? ? '1024' : node[1]['memory_size'].to_s,
      vm_cpu: (@env.cpu_count || node[1]['cpu_count'] || '1').to_s
    }.merge(symbolic_box_params)
  end

  # Log the information about the main parameters of the node.
  #
  # @param node_params [Hash] list of the node parameters
  # @param box [String] name of the box.
  def print_node_info(node_params, box)
    @ui.info("Requested memory #{node_params[:vm_mem]}")
    @ui.info("Requested number of CPUs #{node_params[:vm_cpu]}")
    @ui.info("config.ssh.pty option is #{node_params[:ssh_pty]} for a box #{box}") unless node_params[:ssh_pty].nil?
  end

  # Generate a node definition for the Vagrantfile, depending on the provider
  # uses the appropriate generation method.
  #
  # @param node_params [Hash] list of the node parameters
  # @param cookbook_path [String] path of the cookbook
  # @param path [String] path of the configuration file
  # @return [String] node definition for the Vagrantfile.
  def generate_node_defenition(node_params, cookbook_path, path)
    case node_params[:provider]
    when 'virtualbox'
      get_virtualbox_definition(cookbook_path, node_params)
    when 'libvirt'
      get_libvirt_definition(cookbook_path, path, node_params)
    else
      @ui.warning('Configuration type invalid! It must be vbox libvirt type. Check it, please!')
      ''
    end
  end

  # Parse the products lists from configuration of node.
  #
  # @param node [Array] internal name of the machine specified in the template
  # @return [Array<Hash>] list of parameters of products.
  def parse_products_info(node)
    [{ 'name' => 'packages' }].push(node[1]['product']).push(node[1]['products']).flatten.compact.uniq
  end

  # Make a list of node parameters, create the role and node_config files, generate
  # node definition for the Vagrantfile.
  #
  # @param node [Array] internal name of the machine specified in the template
  # @param path [String] path of the configuration file
  # @param cookbook_path [String] path of the cookbook
  # @return [Result<String>] node definition for the Vagrantfile.
  # rubocop:disable Metrics/MethodLength
  # Further decomposition of the method will complicate the code.
  def node_definition(node, path, cookbook_path)
    box = node[1]['box'].to_s
    unless box.empty?
      node_params = make_node_params(node, @boxes.get_box(box))
      print_node_info(node_params, box)
    end
    products = parse_products_info(node)
    @ui.info("Machine #{node_params[:name]} is provisioned by #{products}")
    get_role_description(node_params[:name], products, box).and_then do |role|
      IO.write(self.class.role_file_name(path, node_params[:name]), role)
      IO.write(self.class.node_config_file_name(path, node_params[:name]),
               JSON.pretty_generate('run_list' => ["role[#{node_params[:name]}]"]))
      # generate node definition
      if box_valid?(box)
        Result.ok(generate_node_defenition(node_params, cookbook_path, path))
      else
        @ui.warning("Box #{box} is not installed or configured ->SKIPPING")
        Result.ok('')
      end
    end
  end
  # rubocop:enable Metrics/MethodLength

  # Generate a Vagrantfile.
  #
  # @param path [String] path of the configuration file
  # @param config [Hash] value of the configuration file
  # @param provider [String] provider name of the nodes
  # @param cookbook_path [String] path of the cookbook.
  # rubocop:disable Metrics/MethodLength
  # The method performs a single function; decomposition of the method will complicate the code.
  def generate_vagrant_file(path, config, provider, cookbook_path)
    vagrant = File.open(File.join(path, 'Vagrantfile'), 'w')
    vagrant.puts vagrant_file_header, vagrant_config_header
    @ui.info('Generating libvirt/VirtualBox configuration')
    vagrant.puts provider_config
    config.each do |node|
      next if node[1]['box'].nil?

      @ui.info("Generating node definition for [#{node[0]}]")
      node_definition = node_definition(node, path, cookbook_path)
      raise node_definition.error if node_definition.error?

      vagrant.puts node_definition.value
    end
    vagrant.puts vagrant_config_footer
    vagrant.close
    SUCCESS_RESULT
  rescue RuntimeError => e
    @ui.error(e.message)
    @ui.error('Configuration is invalid')
    vagrant.close
    FileUtils.rm_rf(path)
    ERROR_RESULT
  end
  # rubocop:enable Metrics/MethodLength

  # Check parameters and generate a Vagrantfile.
  #
  # @param path [String] path of the configuration file
  # @param config [Hash] value of the configuration file
  # @param override [Bool] clean directory if it is already exists
  # @param provider [String] provider name of the nodes
  # @return [Integer] SUCCESS_RESULT if the execution of the method passed without errors,
  # otherwise - ERROR_RESULT or ARGUMENT_ERROR_RESULT.
  def generate(path, config, override, provider)
    # TODO: MariaDb Version Validator
    checks_result = check_path(path, override) && check_nodes_names(config)
    return ARGUMENT_ERROR_RESULT unless checks_result

    cookbook_path = if config['cookbook_path'].nil?
                      File.join(@env.mdbci_dir, 'assets', 'chef-recipes', 'cookbooks') # default cookbook path
                    else
                      config['cookbook_path']
                    end
    @ui.info("Global cookbook_path = #{cookbook_path}")
    @ui.info("Nodes provider = #{provider}")
    return ERROR_RESULT if generate_vagrant_file(path, config, provider, cookbook_path) == ERROR_RESULT
    return SUCCESS_RESULT unless File.size?(File.join(path, 'Vagrantfile')).nil?

    @ui.error('Generated Vagrantfile is empty! Please check configuration file and regenerate it.')
    ERROR_RESULT
  end

  # Generate provider and template files in the configuration directory.
  #
  # @param path [String] configuration directory
  # @param provider [String] nodes provider
  # @raise RuntimeError if provider or template files already exists.
  def generate_provider_and_template_files(path, provider)
    provider_file = File.join(path, 'provider')
    template_file = File.join(path, 'template')
    raise 'Configuration \'provider\' file already exists' if File.exist?(provider_file)
    raise 'Configuration \'template\' file already exists' if File.exist?(template_file)

    File.open(provider_file, 'w') { |f| f.write(provider) }
    File.open(template_file, 'w') { |f| f.write(File.expand_path(@env.template_file)) }
  end

  # Check that all boxes specified in the the template are identical.
  #
  # @param providers [Array] list of nodes providers from config file
  # @return [Bool] false if unable to detect the provider for all boxes or
  # there are several providers in the template, otherwise - true.
  def check_providers(providers)
    if providers.empty?
      @ui.error('Unable to detect the provider for all boxes. Please fix the template.')
      return false
    end
    unique_providers = Set.new(providers)
    return true if unique_providers.size == 1

    @ui.error("There are several node providers defined in the template: #{unique_providers.to_a.join(', ')}.\n"\
              'You can specify only nodes from one provider in the template.')
    false
  end

  # Check that all boxes specified in the the template are exist in the boxes.json
  # and all providers specified in the the template are identical.
  # Save provider to the @provider if check successful.
  #
  # @param configs [Array] list of nodes specified in template
  # @return [Bool] true if the result of passing all checks successful, otherwise - false.
  def load_nodes_provider_and_check_it(configs)
    nodes = configs.map { |node| %w[aws_config cookbook_path].include?(node[0]) ? nil : node }.compact.to_h
    providers = nodes.map do |node_name, node_params|
      box = node_params['box'].to_s
      if box.empty?
        @ui.error("Box in #{node_name} is not found")
        return false
      end

      begin
        box_params = @boxes.get_box(box)
      rescue StandardError
        @ui.error("Box #{box} is not found")
        return false
      end
      box_params['provider'].to_s
    end
    return false unless check_providers(providers)

    @provider = providers.first
    true
  end

  # Set required parameters as instance variables,
  # defines the path for generating the configuration, parse the config JSON-file.
  #
  # @param name [String] name of the configuration file
  # @return [Array<String, Hash>] path and config hash
  # @raise RuntimeError if configuration file is invalid.
  def setup_command(name)
    @boxes = @env.box_definitions
    @configuration_path = name.nil? ? File.join(Dir.pwd, 'default') : File.absolute_path(name.to_s)
    begin
      instance_config_file = IO.read(@env.template_file)
      config = JSON.parse(instance_config_file)
    rescue IOError, JSON::ParserError
      raise('Instance configuration file is invalid or not found!')
    end
    [@configuration_path, config]
  end

  # Generate a configuration.
  #
  # @param name [String] name of the configuration file
  # @param override [Bool] clean directory if it is already exists
  # @return [Number] exit code for the command execution
  def execute(name, override)
    begin
      path, config = setup_command(name)
    rescue RuntimeError => error
      @ui.error(error.message)
      return ERROR_RESULT
    end
    nodes_checking_result = load_nodes_provider_and_check_it(config)
    return ARGUMENT_ERROR_RESULT unless nodes_checking_result

    generate_result = generate(path, config, override, @provider)
    return generate_result unless generate_result == SUCCESS_RESULT

    @ui.info "Generating config in #{path}"
    generate_provider_and_template_files(path, @provider)
    SUCCESS_RESULT
  end
end
# rubocop:enable Metrics/ClassLength
