source 'https://rubygems.org'

group :lint do
  gem 'foodcritic', '~> 4.0'
  gem 'rainbow', '< 2.0'
  gem 'rake'
  gem 'rubocop', '~> 0.18'
end

group :unit do
  gem 'berkshelf', '~> 3.2'
  gem 'chefspec', '~> 4.2'
end

group :kitchen_common do
  gem 'test-kitchen', '~> 1.3'
end

group :development do
  gem 'growl'
  gem 'guard', '~> 2.4'
  gem 'guard-foodcritic'
  gem 'guard-kitchen'
  gem 'guard-rspec'
  gem 'guard-rubocop'
  gem 'rb-fsevent'
  gem 'ruby_gntp'
end
