name             'google-authenticator'
maintainer       'mariadb-corporation'
maintainer_email 'evgeny.vlasov@fruct.org'
license          'All rights reserved'
description      'Install google-authenticator package'
version          '0.1.0'
