name             'mema_agent'
maintainer       'Yaroslavl FRUCT Laboratory'
maintainer_email 'yarfruct@gmail.com'
license          'All rights reserved'
description      'MariaDB Enterprise Manager Agent is an agent that runs on the MariaDB nodes and collects metrics, manages backups and provides services for the MariaDB Enterprise Manager.'
version          '0.1.0'