name             'version_checker'
maintainer       'Yaroslavl FRUCT Laboratory'
maintainer_email 'yarfruct@gmail.com'
license          'All rights reserved'
description      'Allows to check the version of installed DEB, RHEL and SLES packages'
version          '0.1.0'
